version: '3.8'

services:
  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: shop_nginx
    restart: unless-stopped
    ports:
      - "8080:80"      # HTTP trên port 8080
      - "8443:443"     # HTTPS trên port 8443
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - shop_network

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=shop_db
      - DB_USERNAME=shop_user
      - DB_PASSWORD=shop_password
    depends_on:
      - mysql
    networks:
      - shop_network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: shop_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"  # MySQL trên port 3307 (localhost only)
    networks:
      - shop_network

  # Redis (Optional - for caching and sessions)
  redis:
    image: redis:alpine
    container_name: shop_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"  # Redis trên port 6380 (localhost only)
    networks:
      - shop_network

  # PHPMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: shop_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: shop_user
      PMA_PASSWORD: shop_password
    ports:
      - "8081:80"  # PHPMyAdmin trên port 8081
    depends_on:
      - mysql
    networks:
      - shop_network

# Docker Networks
networks:
  shop_network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local 